### ISSUE TITLE
Relative/absolute record name conversions

### ISSUE THREAD

**Issue by mholt** [libdns/alidns#1]
Hi,

Over in the libdns repo, we're discussing standardizing the use of relative or absolute record names in `libdns.Record` structs. The current consensus is that they should be made relative (i.e. for a record named `sub.example.com` in a zone called `example.com`, the name should become `sub`). This may affect your provider implementation.

When you have a chance, would you please check out [this issue](https://github.com/libdns/libdns/issues/12#issuecomment-756135908)? This is the last call for feedback before we decide and I push the changes, and I want to make sure we get it right for the majority of DNS provider implementations so we don't have to change it again.

Link: https://github.com/libdns/libdns/issues/12#issuecomment-756135908

Thank you!

**Comment by viscropst** [comment]
Thanks for your notification. I'll stay tuned with the conversation of `libdns.Record.Name`.

**Comment by francislavoie** [comment]
@viscropst just a reminder that this needs to be addressed. The changes to libdns have been merged, and the latest beta of Caddy uses the changes. This library needs an update to be made compatible, I think. A user seems to be having trouble with it: https://caddy.community/t/how-to-make-caddy-use-not-443-port-for-https/12314

**Comment by viscropst** [comment]
Okay,I'll address and solve this later. Thanks for reminding!

**Comment by mholt** [comment]
(Sorry, forgot about this issue!)

After much discussion we settled on using relative names with conversion functions.

Thanks for maintaining your libdns repo!
